### ISSUE TITLE
electron dependency breaks on travis

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively4-core#259]
```
> electron@1.7.9 postinstall /home/travis/build/LivelyKernel/lively4-core/node_modules/electron
> node install.js
/home/travis/build/LivelyKernel/lively4-core/node_modules/electron/node_modules/electron-download/node_modules/nugget/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/travis/build/LivelyKernel/lively4-core/node_modules/electron/node_modules/electron-download/node_modules/nugget/node_modules/request/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by JensLincke** [comment]
@BJennWare , any ideas? https://travis-ci.org/LivelyKernel/lively4-core/builds/298033013

**Comment by JensLincke** [comment]
not any more
